name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      # Install NestJS CLI globally
      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      # Build the backend using npx to avoid permission issues
      - name: Build backend
        run: npx nest build
        working-directory: backend

      # Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend

      # Run backend tests using npx
      - name: Run backend tests
        run: npx jest
        working-directory: backend

      # Run frontend tests (if available)
      - name: Run frontend tests
        run: npm test
        working-directory: frontend