name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      # Build the backend
      - name: Build backend
        run: npm run dev
        working-directory: backend

      # Build the frontend
      - name: Build frontend
        run: npm run dev
        working-directory: frontend

      # Run backend tests
      - name: Run backend tests
        run: npm test
        working-directory: backend

      # Run frontend tests (if available)
      - name: Run frontend tests
        run: npm test
        working-directory: frontend
